/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{js,jsx,ts,tsx}', './App.{js,jsx,ts,tsx}'],
	presets: [require('nativewind/preset')],
	theme: {
		extend: {
			colors: {
				'primary-1': 'var(--color-primary-1)',
				'primary-2': 'var(--color-primary-2)',
				'primary-3': 'var(--color-primary-3)',
				danger: '#EF4444',
				warning: '#F59E0B',
				surface: '#F9FAFB',
				card: '#FFFFFF',
				g: {
					50: '#f9fafb',
					100: '#f3f4f6',
					200: '#e5e7eb',
					300: '#d1d5db',
					400: '#9ca3af',
					500: '#6b7280',
					600: '#4b5563',
					700: '#374151',
					800: '#1f2937',
					900: '#111827',
				},
			},
			fontFamily: {
				sans: ['Exo-Regular'],
				exo: ['Exo-Regular'],
				'exo-thin': ['Exo-Thin'],
				'exo-thin-italic': ['Exo-ThinItalic'],
				'exo-extralight': ['Exo-ExtraLight'],
				'exo-extralight-italic': ['Exo-ExtraLightItalic'],
				'exo-light': ['Exo-Light'],
				'exo-light-italic': ['Exo-LightItalic'],
				'exo-medium': ['Exo-Medium'],
				'exo-medium-italic': ['Exo-MediumItalic'],
				'exo-semibold': ['Exo-SemiBold'],
				'exo-semibold-italic': ['Exo-SemiBoldItalic'],
				'exo-bold': ['Exo-Bold'],
				'exo-bold-italic': ['Exo-BoldItalic'],
				'exo-extrabold': ['Exo-ExtraBold'],
				'exo-extrabold-italic': ['Exo-ExtraBoldItalic'],
				'exo-black': ['Exo-Black'],
				'exo-black-italic': ['Exo-BlackItalic'],
				'exo-italic': ['Exo-Italic'],
			},
		},
	},
	plugins: [],
};
