/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{js,jsx,ts,tsx}', './App.{js,jsx,ts,tsx}'],
	presets: [require('nativewind/preset')],
	theme: {
		extend: {
			colors: {
				'primary-1': 'var(--color-primary-1)',
				'primary-2': 'var(--color-primary-2)',
				'primary-3': 'var(--color-primary-3)',
				danger: '#EF4444',
				warning: '#F59E0B',
				surface: '#F9FAFB',
				card: '#FFFFFF',
				g: {
					50: 'var(--color-g-50)',
					100: 'var(--color-g-100)',
					200: 'var(--color-g-200)',
					300: 'var(--color-g-300)',
					400: 'var(--color-g-400)',
					500: 'var(--color-g-500)',
					600: 'var(--color-g-600)',
					700: 'var(--color-g-700)',
					800: 'var(--color-g-800)',
					900: 'var(--color-g-900)',
				},
			},
			fontFamily: {
				sans: ['Exo-Regular'],
				exo: ['Exo-Regular'],
				'exo-thin': ['Exo-Thin'],
				'exo-thin-italic': ['Exo-ThinItalic'],
				'exo-extralight': ['Exo-ExtraLight'],
				'exo-extralight-italic': ['Exo-ExtraLightItalic'],
				'exo-light': ['Exo-Light'],
				'exo-light-italic': ['Exo-LightItalic'],
				'exo-medium': ['Exo-Medium'],
				'exo-medium-italic': ['Exo-MediumItalic'],
				'exo-semibold': ['Exo-SemiBold'],
				'exo-semibold-italic': ['Exo-SemiBoldItalic'],
				'exo-bold': ['Exo-Bold'],
				'exo-bold-italic': ['Exo-BoldItalic'],
				'exo-extrabold': ['Exo-ExtraBold'],
				'exo-extrabold-italic': ['Exo-ExtraBoldItalic'],
				'exo-black': ['Exo-Black'],
				'exo-black-italic': ['Exo-BlackItalic'],
				'exo-italic': ['Exo-Italic'],
			},
		},
	},
	plugins: [],
};
